spring:
  profiles:
    active:
      - admin
---
server:
 port: 8080
spring:
 application:
   name: isryancloud-config-admin
 profiles: admin

logging: false

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://admin:enjoy@localhost:7001/eureka
  instance:
    instance-id: isryancloud-config-admin
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔（默认是90秒）

info:
  app.name: isryancloud-admin
  company.name: admin
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
