spring:
  profiles:
    active:
      - eureka
---
server:
  port: 7001

eureka:
  instance: # eureak实例定义
    hostname: eureka # 定义 Eureka 实例所在的主机名称
  client:
    fetch-registry: false #是否从注册中心获取信息
    register-with-eureka: false  #是否注册到eureka
    service-url:
      defaultZone: http://admin:ryan@eureka1:7001/eureka #注册地址
  server:
    eviction-interval-timer-in-ms: 30000 #设置清理时间
    enable-self-preservation: true #关闭保护模式

spring:
  profiles: eureka
  security:
    user:
      name: admin
      password: ryan
  application:
    name: isryancloud-config-eureka
